# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rankine.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1050, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(1050, 700))
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 991, 651))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 931, 281))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Calculate_butt = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Calculate_butt.sizePolicy().hasHeightForWidth())
        self.Calculate_butt.setSizePolicy(sizePolicy)
        self.Calculate_butt.setObjectName("Calculate_butt")
        self.gridLayout_2.addWidget(self.Calculate_butt, 5, 5, 1, 1)
        self.T_High = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.T_High.setObjectName("T_High")
        self.gridLayout_2.addWidget(self.T_High, 5, 1, 1, 1)
        self.Units3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Units3.sizePolicy().hasHeightForWidth())
        self.Units3.setSizePolicy(sizePolicy)
        self.Units3.setObjectName("Units3")
        self.gridLayout_2.addWidget(self.Units3, 5, 3, 1, 1)
        self.Units1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Units1.sizePolicy().hasHeightForWidth())
        self.Units1.setSizePolicy(sizePolicy)
        self.Units1.setObjectName("Units1")
        self.gridLayout_2.addWidget(self.Units1, 3, 3, 1, 1)
        self.phigh_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.phigh_label.setObjectName("phigh_label")
        self.gridLayout_2.addWidget(self.phigh_label, 4, 1, 1, 1)
        self.Quality = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.Quality.setObjectName("Quality")
        self.gridLayout_2.addWidget(self.Quality, 3, 5, 1, 1)
        self.Units2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Units2.sizePolicy().hasHeightForWidth())
        self.Units2.setSizePolicy(sizePolicy)
        self.Units2.setObjectName("Units2")
        self.gridLayout_2.addWidget(self.Units2, 4, 3, 1, 1)
        self.plow_in = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plow_in.sizePolicy().hasHeightForWidth())
        self.plow_in.setSizePolicy(sizePolicy)
        self.plow_in.setObjectName("plow_in")
        self.gridLayout_2.addWidget(self.plow_in, 3, 2, 1, 1)
        self.thigh_in = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thigh_in.sizePolicy().hasHeightForWidth())
        self.thigh_in.setSizePolicy(sizePolicy)
        self.thigh_in.setObjectName("thigh_in")
        self.gridLayout_2.addWidget(self.thigh_in, 5, 2, 1, 1)
        self.plow_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plow_label.sizePolicy().hasHeightForWidth())
        self.plow_label.setSizePolicy(sizePolicy)
        self.plow_label.setObjectName("plow_label")
        self.gridLayout_2.addWidget(self.plow_label, 3, 1, 1, 1)
        self.phigh_in = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phigh_in.sizePolicy().hasHeightForWidth())
        self.phigh_in.setSizePolicy(sizePolicy)
        self.phigh_in.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.phigh_in.setObjectName("phigh_in")
        self.gridLayout_2.addWidget(self.phigh_in, 4, 2, 1, 1)
        self.Temp = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.Temp.setObjectName("Temp")
        self.gridLayout_2.addWidget(self.Temp, 4, 5, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 4, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 4, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 4, 6, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(19, 19, 951, 291))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 2, 7, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 7, 1, 1)
        self.h4_out = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.h4_out.sizePolicy().hasHeightForWidth())
        self.h4_out.setSizePolicy(sizePolicy)
        self.h4_out.setObjectName("h4_out")
        self.gridLayout_3.addWidget(self.h4_out, 3, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 3, 5, 1, 1)
        self.h3_out = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.h3_out.sizePolicy().hasHeightForWidth())
        self.h3_out.setSizePolicy(sizePolicy)
        self.h3_out.setObjectName("h3_out")
        self.gridLayout_3.addWidget(self.h3_out, 2, 2, 1, 1)
        self.label_h4 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_h4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_h4.setObjectName("label_h4")
        self.gridLayout_3.addWidget(self.label_h4, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 5, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 1, 0, 1, 1)
        self.TW_out = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TW_out.sizePolicy().hasHeightForWidth())
        self.TW_out.setSizePolicy(sizePolicy)
        self.TW_out.setAlignment(QtCore.Qt.AlignCenter)
        self.TW_out.setObjectName("TW_out")
        self.gridLayout_3.addWidget(self.TW_out, 0, 6, 1, 1)
        self.label_h2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_h2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_h2.setObjectName("label_h2")
        self.gridLayout_3.addWidget(self.label_h2, 1, 1, 1, 1)
        self.label_h1 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_h1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_h1.setObjectName("label_h1")
        self.gridLayout_3.addWidget(self.label_h1, 0, 1, 1, 1)
        self.PW_out = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PW_out.sizePolicy().hasHeightForWidth())
        self.PW_out.setSizePolicy(sizePolicy)
        self.PW_out.setAlignment(QtCore.Qt.AlignCenter)
        self.PW_out.setObjectName("PW_out")
        self.gridLayout_3.addWidget(self.PW_out, 1, 6, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 5, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 0, 4, 4, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 7, 1, 1)
        self.h1_out = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.h1_out.sizePolicy().hasHeightForWidth())
        self.h1_out.setSizePolicy(sizePolicy)
        self.h1_out.setObjectName("h1_out")
        self.gridLayout_3.addWidget(self.h1_out, 0, 2, 1, 1)
        self.TE_out = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TE_out.sizePolicy().hasHeightForWidth())
        self.TE_out.setSizePolicy(sizePolicy)
        self.TE_out.setAlignment(QtCore.Qt.AlignCenter)
        self.TE_out.setObjectName("TE_out")
        self.gridLayout_3.addWidget(self.TE_out, 3, 6, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 2, 5, 1, 1)
        self.label_h3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_h3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_h3.setObjectName("label_h3")
        self.gridLayout_3.addWidget(self.label_h3, 2, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 3, 7, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 3, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 3, 1, 1)
        self.HA_out = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HA_out.sizePolicy().hasHeightForWidth())
        self.HA_out.setSizePolicy(sizePolicy)
        self.HA_out.setAlignment(QtCore.Qt.AlignCenter)
        self.HA_out.setObjectName("HA_out")
        self.gridLayout_3.addWidget(self.HA_out, 2, 6, 1, 1)
        self.h2_out = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.h2_out.sizePolicy().hasHeightForWidth())
        self.h2_out.setSizePolicy(sizePolicy)
        self.h2_out.setObjectName("h2_out")
        self.gridLayout_3.addWidget(self.h2_out, 1, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 1, 8, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Ideal Rankine Cycle"))
        self.groupBox_2.setTitle(_translate("Dialog", "Input"))
        self.Calculate_butt.setText(_translate("Dialog", "Calculate"))
        self.T_High.setText(_translate("Dialog", "T_HIgh"))
        self.Units3.setText(_translate("Dialog", "[C]"))
        self.Units1.setText(_translate("Dialog", "[kPa]"))
        self.phigh_label.setText(_translate("Dialog", "P_High"))
        self.Quality.setText(_translate("Dialog", "Use x = 1"))
        self.Units2.setText(_translate("Dialog", "[kPa]"))
        self.plow_label.setText(_translate("Dialog", "P_low"))
        self.Temp.setText(_translate("Dialog", "Use T_High"))
        self.groupBox.setTitle(_translate("Dialog", "Output"))
        self.label_15.setText(_translate("Dialog", "kJ/kg"))
        self.label_5.setText(_translate("Dialog", "kJ/kg"))
        self.label_13.setText(_translate("Dialog", "kJ/kg"))
        self.label_12.setText(_translate("Dialog", "Thermal Efficiency"))
        self.label_h4.setText(_translate("Dialog", "h4"))
        self.label_10.setText(_translate("Dialog", "Pump Work"))
        self.label_h2.setText(_translate("Dialog", "h2"))
        self.label_h1.setText(_translate("Dialog", "h1"))
        self.label_9.setText(_translate("Dialog", "Turbine Work"))
        self.label_14.setText(_translate("Dialog", "kJ/kg"))
        self.label_11.setText(_translate("Dialog", "Heat Added"))
        self.label_h3.setText(_translate("Dialog", "h3"))
        self.label_16.setText(_translate("Dialog", "%"))
        self.label_6.setText(_translate("Dialog", "kJ/kg"))
        self.label_7.setText(_translate("Dialog", "kJ/kg"))
        self.label_8.setText(_translate("Dialog", "kJ/kg"))

