# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(1442, 943)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dialog.sizePolicy().hasHeightForWidth())
        dialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        dialog.setWindowIcon(icon)
        self.gridLayoutWidget = QtWidgets.QWidget(dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 541, 921))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(9, 19, 521, 411))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.end_but = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.end_but.setObjectName("end_but")
        self.gridLayout_3.addWidget(self.end_but, 5, 3, 1, 1)
        self.Yi = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Yi.sizePolicy().hasHeightForWidth())
        self.Yi.setSizePolicy(sizePolicy)
        self.Yi.setObjectName("Yi")
        self.gridLayout_3.addWidget(self.Yi, 3, 1, 1, 1)
        self.maze6 = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maze6.sizePolicy().hasHeightForWidth())
        self.maze6.setSizePolicy(sizePolicy)
        self.maze6.setObjectName("maze6")
        self.gridLayout_3.addWidget(self.maze6, 1, 2, 1, 1)
        self.maze3 = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maze3.sizePolicy().hasHeightForWidth())
        self.maze3.setSizePolicy(sizePolicy)
        self.maze3.setObjectName("maze3")
        self.gridLayout_3.addWidget(self.maze3, 0, 2, 1, 1)
        self.maze4 = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maze4.sizePolicy().hasHeightForWidth())
        self.maze4.setSizePolicy(sizePolicy)
        self.maze4.setObjectName("maze4")
        self.gridLayout_3.addWidget(self.maze4, 0, 3, 1, 1)
        self.maze2 = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maze2.sizePolicy().hasHeightForWidth())
        self.maze2.setSizePolicy(sizePolicy)
        self.maze2.setObjectName("maze2")
        self.gridLayout_3.addWidget(self.maze2, 0, 1, 1, 1)
        self.Xi = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Xi.sizePolicy().hasHeightForWidth())
        self.Xi.setSizePolicy(sizePolicy)
        self.Xi.setObjectName("Xi")
        self.gridLayout_3.addWidget(self.Xi, 2, 1, 1, 1)
        self.Yf = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Yf.sizePolicy().hasHeightForWidth())
        self.Yf.setSizePolicy(sizePolicy)
        self.Yf.setObjectName("Yf")
        self.gridLayout_3.addWidget(self.Yf, 3, 3, 1, 1)
        self.Xf = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Xf.sizePolicy().hasHeightForWidth())
        self.Xf.setSizePolicy(sizePolicy)
        self.Xf.setObjectName("Xf")
        self.gridLayout_3.addWidget(self.Xf, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 3, 2, 1, 1)
        self.Ti = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ti.sizePolicy().hasHeightForWidth())
        self.Ti.setSizePolicy(sizePolicy)
        self.Ti.setObjectName("Ti")
        self.gridLayout_3.addWidget(self.Ti, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 2, 0, 1, 1)
        self.maze5 = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maze5.sizePolicy().hasHeightForWidth())
        self.maze5.setSizePolicy(sizePolicy)
        self.maze5.setObjectName("maze5")
        self.gridLayout_3.addWidget(self.maze5, 1, 1, 1, 1)
        self.maze1 = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maze1.sizePolicy().hasHeightForWidth())
        self.maze1.setSizePolicy(sizePolicy)
        self.maze1.setObjectName("maze1")
        self.gridLayout_3.addWidget(self.maze1, 0, 0, 1, 1)
        self.Start_but = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Start_but.sizePolicy().hasHeightForWidth())
        self.Start_but.setSizePolicy(sizePolicy)
        self.Start_but.setObjectName("Start_but")
        self.gridLayout_3.addWidget(self.Start_but, 5, 2, 1, 1)
        self.map_but = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.map_but.setObjectName("map_but")
        self.gridLayout_3.addWidget(self.map_but, 5, 1, 1, 1)
        self.rep_area = QtWidgets.QTextEdit(self.groupBox_3)
        self.rep_area.setGeometry(QtCore.QRect(10, 450, 521, 461))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rep_area.sizePolicy().hasHeightForWidth())
        self.rep_area.setSizePolicy(sizePolicy)
        self.rep_area.setObjectName("rep_area")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(10, 430, 251, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(dialog)
        self.graphicsView.setGeometry(QtCore.QRect(590, 80, 801, 800))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setObjectName("graphicsView")
        self.label_8 = QtWidgets.QLabel(dialog)
        self.label_8.setGeometry(QtCore.QRect(590, 50, 441, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Pathplanning Comparison"))
        self.groupBox_3.setTitle(_translate("dialog", "Setup"))
        self.end_but.setText(_translate("dialog", "Exit"))
        self.Yi.setText(_translate("dialog", "5"))
        self.Yi.setPlaceholderText(_translate("dialog", "5"))
        self.maze6.setText(_translate("dialog", "Maze 6"))
        self.maze3.setText(_translate("dialog", "Maze 3"))
        self.maze4.setText(_translate("dialog", "Maze 4"))
        self.maze2.setText(_translate("dialog", "Maze 2"))
        self.Xi.setText(_translate("dialog", "5"))
        self.Xi.setPlaceholderText(_translate("dialog", "5"))
        self.Yf.setText(_translate("dialog", "50"))
        self.Yf.setPlaceholderText(_translate("dialog", "50"))
        self.Xf.setText(_translate("dialog", "50"))
        self.Xf.setPlaceholderText(_translate("dialog", "50"))
        self.label_4.setText(_translate("dialog", "Final X"))
        self.label_5.setText(_translate("dialog", "Final Y"))
        self.Ti.setText(_translate("dialog", "0.5"))
        self.Ti.setPlaceholderText(_translate("dialog", "0.5"))
        self.label_2.setText(_translate("dialog", "Initial Y"))
        self.label_3.setText(_translate("dialog", "Initital Theta"))
        self.label.setText(_translate("dialog", "Initial X"))
        self.maze5.setText(_translate("dialog", "Maze 5"))
        self.maze1.setText(_translate("dialog", "Maze 1"))
        self.Start_but.setText(_translate("dialog", "Start"))
        self.map_but.setText(_translate("dialog", "Load Map"))
        self.label_6.setText(_translate("dialog", "Report"))
        self.label_8.setText(_translate("dialog", "Plotted Trajectories"))

