# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1030, 981)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 951, 731))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(19, 19, 911, 331))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.EQ_out = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.EQ_out.setObjectName("EQ_out")
        self.gridLayout_3.addWidget(self.EQ_out, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_3.addWidget(self.graphicsView, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 921, 341))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.file_line = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.file_line.setObjectName("file_line")
        self.gridLayout_2.addWidget(self.file_line, 0, 1, 1, 4)
        self.calc_but = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.calc_but.setObjectName("calc_but")
        self.gridLayout_2.addWidget(self.calc_but, 2, 4, 1, 1)
        self.Exit_but = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.Exit_but.setObjectName("Exit_but")
        self.gridLayout_2.addWidget(self.Exit_but, 3, 4, 1, 1)
        self.ex_but = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.ex_but.setObjectName("ex_but")
        self.gridLayout_2.addWidget(self.ex_but, 2, 3, 2, 1)
        self.cub_but = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.cub_but.setObjectName("cub_but")
        self.gridLayout_2.addWidget(self.cub_but, 2, 2, 2, 1)
        self.quad_but = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.quad_but.setObjectName("quad_but")
        self.gridLayout_2.addWidget(self.quad_but, 2, 1, 2, 1)
        self.lin_but = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.lin_but.setObjectName("lin_but")
        self.gridLayout_2.addWidget(self.lin_but, 2, 0, 2, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Least Square Curve Fitting"))
        self.groupBox.setTitle(_translate("Dialog", "Output"))
        self.label_2.setText(_translate("Dialog", "Equation"))
        self.groupBox_2.setTitle(_translate("Dialog", "Input"))
        self.label.setText(_translate("Dialog", "File Name"))
        self.calc_but.setText(_translate("Dialog", "Load and Calculate"))
        self.Exit_but.setText(_translate("Dialog", "Exit"))
        self.ex_but.setText(_translate("Dialog", "Exponential"))
        self.cub_but.setText(_translate("Dialog", "Cubic Fit"))
        self.quad_but.setText(_translate("Dialog", "Quadratic Fit"))
        self.lin_but.setText(_translate("Dialog", "Linear Fit"))

