# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OpenGL_2D_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(991, 689)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 40, 961, 631))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setMouseTracking(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.checkBox_Dragging = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_Dragging.setEnabled(True)
        self.checkBox_Dragging.setGeometry(QtCore.QRect(170, 480, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_Dragging.setFont(font)
        self.checkBox_Dragging.setChecked(False)
        self.checkBox_Dragging.setObjectName("checkBox_Dragging")
        self.horizontalSlider_zoom = QtWidgets.QSlider(self.groupBox_3)
        self.horizontalSlider_zoom.setGeometry(QtCore.QRect(340, 480, 181, 22))
        self.horizontalSlider_zoom.setMaximum(200)
        self.horizontalSlider_zoom.setProperty("value", 150)
        self.horizontalSlider_zoom.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_zoom.setObjectName("horizontalSlider_zoom")
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(290, 480, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.pushButton_Exit = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_Exit.setGeometry(QtCore.QRect(810, 560, 112, 34))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_Exit.setFont(font)
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.groupBox_3)
        self.openGLWidget.setGeometry(QtCore.QRect(10, 20, 941, 431))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openGLWidget.sizePolicy().hasHeightForWidth())
        self.openGLWidget.setSizePolicy(sizePolicy)
        self.openGLWidget.setMouseTracking(False)
        self.openGLWidget.setObjectName("openGLWidget")
        self.MouseLocation = QtWidgets.QLineEdit(self.groupBox_3)
        self.MouseLocation.setGeometry(QtCore.QRect(20, 480, 121, 22))
        self.MouseLocation.setText("")
        self.MouseLocation.setAlignment(QtCore.Qt.AlignCenter)
        self.MouseLocation.setObjectName("MouseLocation")
        self.FiringSpeedText = QtWidgets.QLineEdit(self.groupBox_3)
        self.FiringSpeedText.setGeometry(QtCore.QRect(790, 480, 121, 22))
        self.FiringSpeedText.setText("")
        self.FiringSpeedText.setAlignment(QtCore.Qt.AlignCenter)
        self.FiringSpeedText.setObjectName("FiringSpeedText")
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setGeometry(QtCore.QRect(660, 480, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox.setGeometry(QtCore.QRect(240, 530, 441, 81))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_StopAnimation = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_StopAnimation.setGeometry(QtCore.QRect(290, 30, 91, 34))
        self.pushButton_StopAnimation.setObjectName("pushButton_StopAnimation")
        self.pushButton_PauseResumeAnimation = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_PauseResumeAnimation.setGeometry(QtCore.QRect(150, 30, 131, 34))
        self.pushButton_PauseResumeAnimation.setObjectName("pushButton_PauseResumeAnimation")
        self.pushButton_Animate = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Animate.setGeometry(QtCore.QRect(50, 30, 81, 34))
        self.pushButton_Animate.setObjectName("pushButton_Animate")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "OpenGL"))
        self.groupBox_3.setTitle(_translate("Dialog", "OpenGL Simple 2D Drawing"))
        self.checkBox_Dragging.setText(_translate("Dialog", "Dragging"))
        self.label_20.setText(_translate("Dialog", "Zoom"))
        self.pushButton_Exit.setText(_translate("Dialog", "Exit"))
        self.label_21.setText(_translate("Dialog", "Firing Speed"))
        self.groupBox.setTitle(_translate("Dialog", "Animation Controls"))
        self.pushButton_StopAnimation.setText(_translate("Dialog", "Stop"))
        self.pushButton_PauseResumeAnimation.setText(_translate("Dialog", "Pause/Resume"))
        self.pushButton_Animate.setText(_translate("Dialog", "Start"))

